// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBju-hTVu31gw9zuWPHgaVr3SNgJz6zZ6A',
    appId: '1:743408766464:web:0ddccb9dd280792e6352e5',
    messagingSenderId: '743408766464',
    projectId: 'ecommerce-app-b9e8d',
    authDomain: 'ecommerce-app-b9e8d.firebaseapp.com',
    storageBucket: 'ecommerce-app-b9e8d.firebasestorage.app',
    measurementId: 'G-XMLR6KK42E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ZLpfPlKz1BrdojxUZbK690XUyU7qKoo',
    appId: '1:743408766464:android:f4c6357316637a876352e5',
    messagingSenderId: '743408766464',
    projectId: 'ecommerce-app-b9e8d',
    storageBucket: 'ecommerce-app-b9e8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGe9VpJYb_8w_umOd9EHDSaB145P9fdDU',
    appId: '1:743408766464:ios:9460401a8b4bc0a46352e5',
    messagingSenderId: '743408766464',
    projectId: 'ecommerce-app-b9e8d',
    storageBucket: 'ecommerce-app-b9e8d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGe9VpJYb_8w_umOd9EHDSaB145P9fdDU',
    appId: '1:743408766464:ios:9460401a8b4bc0a46352e5',
    messagingSenderId: '743408766464',
    projectId: 'ecommerce-app-b9e8d',
    storageBucket: 'ecommerce-app-b9e8d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBju-hTVu31gw9zuWPHgaVr3SNgJz6zZ6A',
    appId: '1:743408766464:web:76c8675581237dc66352e5',
    messagingSenderId: '743408766464',
    projectId: 'ecommerce-app-b9e8d',
    authDomain: 'ecommerce-app-b9e8d.firebaseapp.com',
    storageBucket: 'ecommerce-app-b9e8d.firebasestorage.app',
    measurementId: 'G-J4P1MT9KEP',
  );
}
